apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flotte-api-ingress
  namespace: flotte-namespace
spec:
  ingressClassName: nginx
  rules:
    - host: flotte.local
      http:
        paths:
          - path: /api/vehicles
            pathType: Prefix
            backend:
              service:
                name: vehicle-service
                port:
                  number: 8080
          - path: /api/drivers
            pathType: Prefix
            backend:
              service:
                name: driver-service
                port:
                  number: 8081
          - path: /api/maintenance
            pathType: Prefix
            backend:
              service:
                name: maintenance-service
                port:
                  number: 8082
