spring.application.name=maintenance-service

flotte.postgres.auto-create-databases=true
flotte.postgres.databases=maintenance_db

# Configuration de la base de données (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/maintenance_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=maintenance-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Mappage des types pour la désérialisation inter-service
spring.kafka.consumer.properties.spring.json.type.mapping=com.flotte.vehicle.events.KafkaEventEnvelope:com.flotte.vehicle.events.KafkaEventEnvelope,com.flotte.vehicle.events.VehiclePayload:com.flotte.vehicle.events.VehiclePayload

# Configuration Keycloak (SSO)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/gestion-flotte/protocol/openid-connect/certs}

# Configuration de l'observabilité
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4317}
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4317}
spring.jackson.property-naming-strategy=SNAKE_CASE
server.port=8080
