apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: flotte-namespace
spec:
  selector:
    app: driver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
