apiVersion: v1
kind: Service
metadata:
  name: maintenance-service
  namespace: flotte-namespace
spec:
  selector:
    app: maintenance # Doit correspondre exactement au label du pod
  ports:
    - name: http
      port: 8082
      targetPort: 8080
  type: ClusterIP
