namespace: flotte-namespace

# 1. Configuration de PostgreSQL
postgresql:
  fullnameOverride: "postgres-service"

  auth:
    postgresUser: "admin"
    database: "flotte_db"
    # Utilisation de secrets pour les mots de passe

  primary:
    persistence:
      enabled: false
    initdb:
      scriptsConfigMap: "vehicle-sql-init"    # ← exécuté au 1er démarrage
      scripts:
        02-seed.sql: |                         # ← ou directement inline
          \i /docker-entrypoint-initdb.d/02-seed.sql

# 2. Configuration de Redis
redis:
  fullnameOverride: "redis-service"

  architecture: "standalone"

  auth:
    enabled: false
  
  master:
    persistence:
      enabled: false

# 3. Configuration de Kafka (KRaft mode)
kafka:
  image: confluentinc/cp-kafka:7.5.0
  port: 9092
