namespace: flotte-namespace

jaeger:
  image: jaegertracing/all-in-one:1.55

prometheus:
  image: prom/prometheus:v2.51.0

loki:
  image: grafana/loki:2.9.4

grafana:
  image: grafana/grafana:10.4.1
  adminPassword: admin

otelCollector:
  image: otel/opentelemetry-collector-contrib:0.96.0

promtail:
  image: grafana/promtail:2.9.4
